model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0000002
        pose:
            lr: 0.0005
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'monoformer'
        version: ''
        backbone : 'twins_base'
        features : 128
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
    loss:
        smooth_loss_weight: 0.0005
        occ_reg_weight : 0.15
        ssim_loss_weight : 0.85

datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 15
        num_workers: 16
        dataset: ['KITTI']
        path: ['DATA_PATH']
        split: ['data_splits/eigen_train_files.txt']
        depth_type: ['velodyne']
        repeat: [2]
    validation:
        dataset: ['KITTI']
        path: ['DATA_PATH']
        split: ['data_splits/eigen_val_files.txt',
                'data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['DATA_PATH']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']


checkpoint:
    filepath: 'checkpoints'
    monitor: 'abs_rel_gt'
    monitor_index: 1
    mode: 'min'

